# Generated by Django 3.2.9 on 2021-12-04 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='likes',
            field=models.ManyToManyField(related_name='posting_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
